package moe.ofs.backend.object.command;

/*
BEACON_TYPE_NULL = 0
BEACON_TYPE_VOR = 1
BEACON_TYPE_DME = 2
BEACON_TYPE_VOR_DME = 3
BEACON_TYPE_TACAN = 4
BEACON_TYPE_VORTAC = 5
BEACON_TYPE_RSBN = 32
BEACON_TYPE_BROADCAST_STATION = 1024
BEACON_TYPE_HOMER = 8
BEACON_TYPE_AIRPORT_HOMER = 4104
BEACON_TYPE_AIRPORT_HOMER_WITH_MARKER = 4136
BEACON_TYPE_ILS_FAR_HOMER = 16408
BEACON_TYPE_ILS_NEAR_HOMER = 16456
BEACON_TYPE_ILS_LOCALIZER = 16640
BEACON_TYPE_ILS_GLIDESLOPE = 16896
BEACON_TYPE_NAUTICAL_HOMER = 32776
*/
public enum BeaconType {
    BEACON_TYPE_NULL(0),
    BEACON_TYPE_VOR(1),
    BEACON_TYPE_DME(2),
    BEACON_TYPE_VOR_DME(3),
    BEACON_TYPE_TACAN(4),
    BEACON_TYPE_VORTAC(5);

    private int type;

    BeaconType(int type) {
        this.type = type;
    }

    public int getType() {
        return type;
    }
}
