package moe.ofs.backend.lavalog;

import moe.ofs.backend.domain.LogEntry;

import java.io.IOException;
import java.util.Set;

/**
 * Add, search and dump log entry generated by {@see LogEntry }
 *
 * Pagination is required for infinite scroll in the frontend Vue project.
 */
public interface LavaSystemLogService {
    /**
     * Find one entry by its ID
     * @param id ID of the LogEntry
     * @return LogEntry object
     */
    LogEntry findById(Long id);

    /**
     * Insert one LogEntry into a repository
     * @param logEntry the LogEntry object to be inserted
     *
     */
    void save(LogEntry logEntry);

    /**
     * Retrieve all log entries for the current session. When background task starts, it generates a start timestamp.
     * The method should return all logs that are generated after this timestamp, with pagination
     * @return
     */
    Set<LogEntry> findAllForCurrentSession();

    /**
     * Write selected logs to json or csv file. Takes a File or Path.
     */
    void saveLogFile() throws IOException;


}
